name: Build the application

on:
 workflow_call:
  inputs:
    environment:
      type: string
      required: true
    docker_image_name:
      type: string
      required: true
    docker_image_tag:
      type: string
      required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and load Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: |
            ${{ inputs.docker_image_name }}:${{ inputs.docker_image_tag }}
            ${{ vars.DOCKERHUB_USERNAME }}/${{ inputs.docker_image_name }}:${{ inputs.docker_image_tag }}
            ${{ vars.DOCKERHUB_USERNAME }}/${{ inputs.docker_image_name }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ inputs.docker_image_name }}:${{ inputs.docker_image_tag }}
            ${{ vars.DOCKERHUB_USERNAME }}/${{ inputs.docker_image_name }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Cleanup
        if: always()
        run: |
          docker image remove ${{ vars.DOCKERHUB_USERNAME }}/${{ inputs.docker_image_name }}:${{ github.sha }}