name: Dev Node.js Pipeline

on:
  push:
    branches: [dev]

env:
  APP_PORT: 4000

jobs:
  test-node:
    uses: reusdevops/cicd/.github/workflows/test-node.yaml@dev
    permissions:
      contents: write
    with:
      environment: dev
    secrets: inherit

  build:
    needs: test-node
    uses: reusdevops/cicd/.github/workflows/build.yaml@dev
    permissions:
      contents: write
    with:
      environment: dev
      docker_image_name: transcoding
      docker_image_tag: latest
    secrets: inherit

  deploy:
    needs: build
    uses: reusdevops/cicd/.github/workflows/deploy.yaml@dev
    permissions:
      contents: write
    with:
      environment: dev
    secrets: inherit