name: Dev Node.js Pipeline

on:
  push:
    branches: [dev]

env:
  APP_PORT: 4000

jobs:
  test-node:
    uses: reusdevops/cicd/.github/workflows/workflow_call/test-node.yaml@dev
    permissions:
      contents: write
    with:
      environment: dev
    secrets: inherit

  # build:
  #   needs: test-node
  #   uses: ./.github/workflows/build.yaml
  #   permissions:
  #     contents: write
  #   with:
  #     environment: dev
  #     docker_image_name: transcoding
  #     docker_image_tag: latest
  #   secrets: inherit

  # deploy:
  #   needs: build
  #   uses: ./.github/workflows/deploy.yaml
  #   permissions:
  #     contents: write
  #   with:
  #     environment: dev
  #   secrets: inherit