name: Dev Node.js Pipeline

on:
  push:
    branches: [dev]

env:
  APP_PORT: 4000

jobs:
  test-node:
    uses: ./.github/workflows/test-node.yaml
    permissions:
      contents: write
    with:
      environment: dev
    secrets: inherit