name: Testing Application With Container
on:
  workflow_call:
    inputs:
      environment:
        type: string
      docker_image_name:
        type: string
        required: true
      docker_image_tag:
        type: string
        required: true
      container_name: 
        type: string
        required: true
      app_port: 
        type: string
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and load Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: |
            ${{ inputs.docker_image_name }}:${{ inputs.docker_image_tag }}
            ${{ vars.DOCKERHUB_USERNAME }}/${{ inputs.docker_image_name }}:${{ inputs.docker_image_tag }}
            ${{ vars.DOCKERHUB_USERNAME }}/${{ inputs.docker_image_name }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run application container
        run: |
          docker run -d \
            -p ${{ inputs.app_port }}:${{ inputs.app_port }} \
            --name ${{ inputs.container_name }} \
            --health-cmd="curl -f http://localhost:${{ inputs.app_port }} || exit 1" \
            --health-interval=5s \
            --health-timeout=3s \
            --health-retries=3 \
            ${{ inputs.docker_image_name }}:${{ inputs.docker_image_tag }}

      - name: View container logs on failure
        if: failure()
        run: docker logs ${{ inputs.container_name }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ inputs.docker_image_name }}:${{ inputs.docker_image_tag }}
            ${{ vars.DOCKERHUB_USERNAME }}/${{ inputs.docker_image_name }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Cleanup
        if: always()
        run: |
          docker stop ${{ inputs.container_name }} || true
          docker rm ${{ inputs.container_name }} || true