name: Testing Application
on:
  workflow_call:
    inputs:
      name:
        type: string
      environment:
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          version: '20'
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Successfully Installed
        run: echo "Successfully install Node"